#pragma once
#include "pch.h"

// Don't include this file
//#include <mmsystem.h>

// typedefs for types from <mmsystem.h>
typedef DWORD FOURCC;
typedef DWORD HDRVR;
typedef DWORD HMIDIIN;
typedef DWORD HMIDIN;
typedef DWORD HMIDIOUT;
typedef DWORD HMIDISTRM;
typedef DWORD HMIXER;
typedef DWORD HMIXEROBJ;
typedef DWORD HMMIO;
typedef DWORD HWAVEIN;
typedef DWORD HWAVEOUT;
typedef DWORD LPAUXCAPSA;
typedef DWORD LPAUXCAPSW;
typedef DWORD LPCWAVEFORMATEX;
typedef DWORD LPHMIDIIN;
typedef DWORD LPHMIDIOUT;
typedef DWORD LPHMIDISTRM;
typedef DWORD LPHMIXER;
typedef DWORD LPHWAVEIN;
typedef DWORD LPHWAVEOUT;
typedef DWORD LPJOYCAPSA;
typedef DWORD LPJOYCAPSW;
typedef DWORD LPJOYINFO;
typedef DWORD LPJOYINFOEX;
typedef DWORD LPMDRVLP;
typedef DWORD LPMIDIHDR;
typedef DWORD LPMIDIINCAPSA;
typedef DWORD LPMIDIINCAPSW;
typedef DWORD LPMIDIOUTCAPSA;
typedef DWORD LPMIDIOUTCAPSW;
typedef DWORD LPMIXERCAPSA;
typedef DWORD LPMIXERCAPSW;
typedef DWORD LPMIXERCONTROLDETAILS;
typedef DWORD LPMIXERLINEA;
typedef DWORD LPMIXERLINECONTROLSA;
typedef DWORD LPMIXERLINECONTROLSW;
typedef DWORD LPMIXERLINEW;
typedef DWORD LPMMCKINFO;
typedef DWORD LPMMIOINFO;
typedef DWORD LPMMTIME;
typedef DWORD LPTASKENTRY;
typedef DWORD LPTIMECALLBACK;
typedef DWORD LPTIMECAPS;
typedef DWORD LPTIMEINFO;
typedef DWORD LPWAVEHDR;
typedef DWORD LPWAVEINCAPSA;
typedef DWORD LPWAVEINCAPSW;
typedef DWORD LPWAVEOUTCAPSA;
typedef DWORD LPWAVEOUTCAPSW;
typedef DWORD MCIERROR;
typedef DWORD MMRESULT;
typedef DWORD YIELDPROC;
typedef DWORD MMCKINFO;


// Pointer typedefs
typedef LRESULT(WINAPI* CloseDriver_t)(HDRVR hDriver, LPARAM lParam1, LPARAM lParam2);
typedef LRESULT(CALLBACK* DefDriverProc_t)(DWORD_PTR dwDriverIdentifier, HDRVR hDriver, UINT uMsg, LPARAM lParam1, LPARAM lParam2);
typedef void (CALLBACK* DriverCallback_t)(DWORD_PTR dwCallback, DWORD dwFlags, HDRVR hDev, DWORD_PTR dw1, DWORD_PTR dw2);
typedef HMODULE(WINAPI* DrvGetModuleHandle_t)(HDRVR hDriver);
typedef HMODULE(WINAPI* GetDriverModuleHandle_t)(HDRVR hDriver);
typedef HDRVR(WINAPI* OpenDriver_t)(LPCWSTR szDriverName, LPCWSTR szSectionName, LPARAM lParam);
typedef BOOL(WINAPI* PlaySound_t)(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound);
typedef BOOL(WINAPI* PlaySoundA_t)(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound);
typedef BOOL(WINAPI* PlaySoundW_t)(LPCWSTR pszSound, HMODULE hmod, DWORD fdwSound);
typedef LRESULT(WINAPI* SendDriverMessage_t)(HDRVR hDriver, UINT uMsg, LPARAM lParam1, LPARAM lParam2);
typedef void (WINAPI* WOWAppExit_t)(HANDLE hTask);
typedef MMRESULT(WINAPI* auxGetDevCapsA_t)(UINT_PTR uDeviceID, LPAUXCAPSA pac, UINT cbac);
typedef MMRESULT(WINAPI* auxGetDevCapsW_t)(UINT_PTR uDeviceID, LPAUXCAPSW pac, UINT cbac);
typedef UINT(WINAPI* auxGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* auxGetVolume_t)(UINT uDeviceID, LPDWORD lpdwVolume);
typedef MMRESULT(WINAPI* auxOutMessage_t)(UINT uDeviceID, UINT uMsg, DWORD_PTR dw1, DWORD_PTR dw2);
typedef MMRESULT(WINAPI* auxSetVolume_t)(UINT uDeviceID, DWORD dwVolume);
typedef void (WINAPI* joyConfigChanged_t)(DWORD dwFlags);
typedef MMRESULT(WINAPI* joyGetDevCapsA_t)(UINT_PTR uJoyID, LPJOYCAPSA pjc, UINT cbjc);
typedef MMRESULT(WINAPI* joyGetDevCapsW_t)(UINT_PTR uJoyID, LPJOYCAPSW pjc, UINT cbjc);
typedef UINT(WINAPI* joyGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* joyGetPos_t)(UINT uJoyID, LPJOYINFO pji);
typedef MMRESULT(WINAPI* joyGetPosEx_t)(UINT uJoyID, LPJOYINFOEX pji);
typedef MMRESULT(WINAPI* joyGetThreshold_t)(UINT uJoyID, LPUINT puThreshold);
typedef MMRESULT(WINAPI* joyReleaseCapture_t)(UINT uJoyID);
typedef MMRESULT(WINAPI* joySetCapture_t)(HWND hwnd, UINT uJoyID, UINT uPeriod, BOOL fChanged);
typedef MMRESULT(WINAPI* joySetThreshold_t)(UINT uJoyID, UINT uThreshold);
typedef void (WINAPI* mciDriverNotify_t)(HWND hwndCallback, UINT wDeviceID, UINT uStatus);
typedef void (WINAPI* mciDriverYield_t)(UINT uDeviceID);
typedef BOOL(WINAPI* mciExecute_t)(LPCSTR pszCommand);
typedef void (WINAPI* mciFreeCommandResource_t)(UINT_PTR resourceID);
typedef HANDLE(WINAPI* mciGetCreatorTask_t)(UINT uDeviceID);
typedef UINT(WINAPI* mciGetDeviceIDA_t)(LPCSTR pszDevice);
typedef UINT(WINAPI* mciGetDeviceIDFromElementIDA_t)(DWORD dwElementID, LPCSTR lpstrType);
typedef UINT(WINAPI* mciGetDeviceIDFromElementIDW_t)(DWORD dwElementID, LPCWSTR lpstrType);
typedef UINT(WINAPI* mciGetDeviceIDW_t)(LPCWSTR pszDevice);
typedef DWORD_PTR(WINAPI* mciGetDriverData_t)(UINT uDeviceID);
typedef BOOL(WINAPI* mciGetErrorStringA_t)(DWORD fdwError, LPSTR lpszErrorText, UINT cchErrorText);
typedef BOOL(WINAPI* mciGetErrorStringW_t)(DWORD fdwError, LPWSTR lpszErrorText, UINT cchErrorText);
typedef YIELDPROC(WINAPI* mciGetYieldProc_t)(UINT uDeviceID, LPDWORD lpdwYieldData);
typedef UINT_PTR(WINAPI* mciLoadCommandResource_t)(HINSTANCE hInstance, LPCWSTR lpResName, UINT wType);
typedef MCIERROR(WINAPI* mciSendCommandA_t)(UINT mciId, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2);
typedef MCIERROR(WINAPI* mciSendCommandW_t)(UINT mciId, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2);
typedef MCIERROR(WINAPI* mciSendStringA_t)(LPCSTR lpszCommand, LPSTR lpszReturnString, UINT cchReturn, HWND hwndCallback);
typedef MCIERROR(WINAPI* mciSendStringW_t)(LPCWSTR lpszCommand, LPWSTR lpszReturnString, UINT cchReturn, HWND hwndCallback);
typedef BOOL(WINAPI* mciSetDriverData_t)(UINT uDeviceID, DWORD_PTR data);
typedef void (WINAPI* mciSetYieldProc_t)(UINT uDeviceID, YIELDPROC yieldProc, DWORD dwYieldData);
typedef MMRESULT(WINAPI* midiConnect_t)(HMIDIOUT hmo, HMIDIN hmi, LPVOID pReserved);
typedef MMRESULT(WINAPI* midiDisconnect_t)(HMIDIOUT hmo, HMIDIN hmi, LPVOID pReserved);
typedef MMRESULT(WINAPI* midiInAddBuffer_t)(HMIDIIN hmi, LPMIDIHDR lpMidiInHdr, UINT cbMidiInHdr);
typedef MMRESULT(WINAPI* midiInClose_t)(HMIDIIN hMidiIn);
typedef MMRESULT(WINAPI* midiInGetDevCapsA_t)(UINT_PTR uDeviceID, LPMIDIINCAPSA pmic, UINT cbmic);
typedef MMRESULT(WINAPI* midiInGetDevCapsW_t)(UINT_PTR uDeviceID, LPMIDIINCAPSW pmic, UINT cbmic);
typedef MMRESULT(WINAPI* midiInGetErrorTextA_t)(MMRESULT mmrError, LPSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* midiInGetErrorTextW_t)(MMRESULT mmrError, LPWSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* midiInGetID_t)(HMIDIIN hMidiIn, LPUINT puDeviceID);
typedef UINT(WINAPI* midiInGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* midiInMessage_t)(HMIDIIN hMidiIn, UINT uMessage, DWORD_PTR dw1, DWORD_PTR dw2);
typedef MMRESULT(WINAPI* midiInOpen_t)(LPHMIDIIN phMidiIn, UINT uDeviceID, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* midiInPrepareHeader_t)(HMIDIIN hMidiIn, LPMIDIHDR pMidiInHdr, UINT cbMidiInHdr);
typedef MMRESULT(WINAPI* midiInReset_t)(HMIDIIN hMidiIn);
typedef MMRESULT(WINAPI* midiInStart_t)(HMIDIIN hMidiIn);
typedef MMRESULT(WINAPI* midiInStop_t)(HMIDIIN hMidiIn);
typedef MMRESULT(WINAPI* midiInUnprepareHeader_t)(HMIDIIN hMidiIn, LPMIDIHDR pMidiInHdr, UINT cbMidiInHdr);
typedef MMRESULT(WINAPI* midiOutCacheDrumPatches_t)(HMIDIOUT hmo, UINT uPatch, WORD wBank, UINT wCount);
typedef MMRESULT(WINAPI* midiOutCachePatches_t)(HMIDIOUT hmo, UINT uBank, UINT wStartPatch, UINT wCount);
typedef MMRESULT(WINAPI* midiOutClose_t)(HMIDIOUT hMidiOut);
typedef MMRESULT(WINAPI* midiOutGetDevCapsA_t)(UINT_PTR uDeviceID, LPMIDIOUTCAPSA pmoc, UINT cbmoc);
typedef MMRESULT(WINAPI* midiOutGetDevCapsW_t)(UINT_PTR uDeviceID, LPMIDIOUTCAPSW pmoc, UINT cbmoc);
typedef MMRESULT(WINAPI* midiOutGetErrorTextA_t)(MMRESULT mmrError, LPSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* midiOutGetErrorTextW_t)(MMRESULT mmrError, LPWSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* midiOutGetID_t)(HMIDIOUT hMidiOut, LPUINT puDeviceID);
typedef UINT(WINAPI* midiOutGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* midiOutGetVolume_t)(HMIDIOUT hMidiOut, LPDWORD lpdwVolume);
typedef MMRESULT(WINAPI* midiOutLongMsg_t)(HMIDIOUT hMidiOut, LPMIDIHDR pMidiOutHdr, UINT cbMidiOutHdr);
typedef MMRESULT(WINAPI* midiOutMessage_t)(HMIDIOUT hMidiOut, UINT uMessage, DWORD_PTR dw1, DWORD_PTR dw2);
typedef MMRESULT(WINAPI* midiOutOpen_t)(LPHMIDIOUT phMidiOut, UINT uDeviceID, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* midiOutPrepareHeader_t)(HMIDIOUT hMidiOut, LPMIDIHDR pMidiOutHdr, UINT cbMidiOutHdr);
typedef MMRESULT(WINAPI* midiOutReset_t)(HMIDIOUT hMidiOut);
typedef MMRESULT(WINAPI* midiOutSetVolume_t)(HMIDIOUT hMidiOut, DWORD dwVolume);
typedef MMRESULT(WINAPI* midiOutShortMsg_t)(HMIDIOUT hMidiOut, DWORD dwMsg);
typedef MMRESULT(WINAPI* midiOutUnprepareHeader_t)(HMIDIOUT hMidiOut, LPMIDIHDR pMidiOutHdr, UINT cbMidiOutHdr);
typedef MMRESULT(WINAPI* midiStreamClose_t)(HMIDISTRM hStream);
typedef MMRESULT(WINAPI* midiStreamOpen_t)(LPHMIDISTRM phStream, LPUINT puDeviceID, UINT cMidi, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* midiStreamOut_t)(HMIDISTRM hStream, LPMIDIHDR pmh, UINT cbmh);
typedef MMRESULT(WINAPI* midiStreamPause_t)(HMIDISTRM hStream);
typedef MMRESULT(WINAPI* midiStreamPosition_t)(HMIDISTRM hStream, LPMMTIME pmmt, UINT cbmmt);
typedef MMRESULT(WINAPI* midiStreamProperty_t)(HMIDISTRM hStream, LPBYTE lppropdata, DWORD dwproperty);
typedef MMRESULT(WINAPI* midiStreamRestart_t)(HMIDISTRM hStream);
typedef MMRESULT(WINAPI* midiStreamStop_t)(HMIDISTRM hStream);
typedef MMRESULT(WINAPI* mixerClose_t)(HMIXER hmx);
typedef MMRESULT(WINAPI* mixerGetControlDetailsA_t)(HMIXEROBJ hmxobj, LPMIXERCONTROLDETAILS pmxcd, DWORD fdwDetails);
typedef MMRESULT(WINAPI* mixerGetControlDetailsW_t)(HMIXEROBJ hmxobj, LPMIXERCONTROLDETAILS pmxcd, DWORD fdwDetails);
typedef MMRESULT(WINAPI* mixerGetDevCapsA_t)(UINT_PTR uMxId, LPMIXERCAPSA pmxcaps, UINT cbxcaps);
typedef MMRESULT(WINAPI* mixerGetDevCapsW_t)(UINT_PTR uMxId, LPMIXERCAPSW pmxcaps, UINT cbxcaps);
typedef MMRESULT(WINAPI* mixerGetID_t)(HMIXEROBJ hmxobj, LPUINT puMxId, DWORD fdwMeas);
typedef UINT(WINAPI* mixerGetLineControlsA_t)(HMIXEROBJ hmxobj, LPMIXERLINECONTROLSA pmxlc, DWORD fdwControls);
typedef UINT(WINAPI* mixerGetLineControlsW_t)(HMIXEROBJ hmxobj, LPMIXERLINECONTROLSW pmxlc, DWORD fdwControls);
typedef MMRESULT(WINAPI* mixerGetLineInfoA_t)(HMIXEROBJ hmxobj, LPMIXERLINEA pmxl, DWORD fdwInfo);
typedef MMRESULT(WINAPI* mixerGetLineInfoW_t)(HMIXEROBJ hmxobj, LPMIXERLINEW pmxl, DWORD fdwInfo);
typedef UINT(WINAPI* mixerGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* mixerMessage_t)(HMIXER hmx, UINT uMsg, DWORD_PTR dwParam1, DWORD_PTR dwParam2);
typedef MMRESULT(WINAPI* mixerOpen_t)(LPHMIXER phmx, UINT uMxId, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* mixerSetControlDetails_t)(HMIXEROBJ hmxobj, LPMIXERCONTROLDETAILS pmxcd, DWORD fdwDetails);
typedef MMRESULT(WINAPI* mmDrvInstall_t)(LPMDRVLP lpmdrv, UINT uidDriver, UINT uFlags);
typedef DWORD(WINAPI* mmGetCurrentTask_t)(void);
typedef BOOLEAN(WINAPI* mmTaskBlock_t)(DWORD dwTimeout);
typedef DWORD(WINAPI* mmTaskCreate_t)(LPTASKENTRY lpTaskEntry, LPSTR lpszTaskName, WORD wStackSize, WORD wPriority, LPARAM lParamInit);
typedef BOOLEAN(WINAPI* mmTaskSignal_t)(DWORD dwTaskID, DWORD dwEvent);
typedef void (WINAPI* mmTaskYield_t)(void);
typedef MMRESULT(WINAPI* mmioAdvance_t)(HMMIO hmmio, LPMMIOINFO lpmmioinfo, UINT wFlags);
typedef MMRESULT(WINAPI* mmioAscend_t)(HMMIO hmmio, LPMMCKINFO lpck, UINT wFlags);
typedef MMRESULT(WINAPI* mmioClose_t)(HMMIO hmmio, UINT wFlags);
typedef MMRESULT(WINAPI* mmioCreateChunk_t)(HMMIO hmmio, LPMMCKINFO lpck, UINT wFlags);
typedef MMRESULT(WINAPI* mmioDescend_t)(HMMIO hmmio, LPMMCKINFO lpck, const MMCKINFO* lpckParent, UINT wFlags);
typedef MMRESULT(WINAPI* mmioFlush_t)(HMMIO hmmio, UINT wFlags);
typedef MMRESULT(WINAPI* mmioGetInfo_t)(HMMIO hmmio, LPMMIOINFO lpmmioinfo, UINT wFlags);
typedef FOURCC(WINAPI* mmioInstallIOProcA_t)(FOURCC fccIOProc, LPMMIOINFO lpmmioinfo, DWORD dwFlags);
typedef FOURCC(WINAPI* mmioInstallIOProcW_t)(FOURCC fccIOProc, LPMMIOINFO lpmmioinfo, DWORD dwFlags);
typedef HMMIO(WINAPI* mmioOpenA_t)(LPCSTR szFilename, LPMMIOINFO lpmmioinfo, DWORD dwOpenFlags);
typedef HMMIO(WINAPI* mmioOpenW_t)(LPCWSTR szFilename, LPMMIOINFO lpmmioinfo, DWORD dwOpenFlags);
typedef LONG(WINAPI* mmioRead_t)(HMMIO hmmio, LPSTR pch, LONG cch);
typedef MMRESULT(WINAPI* mmioRenameA_t)(LPCSTR pszFileOld, LPCSTR pszFileNew, UINT wFlags);
typedef MMRESULT(WINAPI* mmioRenameW_t)(LPCWSTR pszFileOld, LPCWSTR pszFileNew, UINT wFlags);
typedef LONG(WINAPI* mmioSeek_t)(HMMIO hmmio, LONG lOffset, int iOrigin);
typedef LRESULT(WINAPI* mmioSendMessage_t)(HMMIO hmmio, UINT uMsg, LPARAM lParam1, LPARAM lParam2);
typedef MMRESULT(WINAPI* mmioSetBuffer_t)(HMMIO hmmio, LPSTR pchBuffer, LONG cchBuffer, UINT wFlags);
typedef MMRESULT(WINAPI* mmioSetInfo_t)(HMMIO hmmio, LPMMIOINFO lpmmioinfo, UINT wFlags);
typedef FOURCC(WINAPI* mmioStringToFOURCCA_t)(LPCSTR sz);
typedef FOURCC(WINAPI* mmioStringToFOURCCW_t)(LPCWSTR sz);
typedef LONG(WINAPI* mmioWrite_t)(HMMIO hmmio, const char* pch, LONG cch);
typedef UINT(WINAPI* mmsystemGetVersion_t)(void);
typedef BOOL(WINAPI* sndPlaySoundA_t)(LPCSTR pszSound, UINT fuSound);
typedef BOOL(WINAPI* sndPlaySoundW_t)(LPCWSTR pszSound, UINT fuSound);
typedef MMRESULT(WINAPI* timeBeginPeriod_t)(UINT uPeriod);
typedef MMRESULT(WINAPI* timeEndPeriod_t)(UINT uPeriod);
typedef MMRESULT(WINAPI* timeGetDevCaps_t)(LPTIMECAPS ptc, UINT cbtc);
typedef void (WINAPI* timeGetSystemTime_t)(LPTIMEINFO pti, UINT cbti);
typedef DWORD(WINAPI* timeGetTime_t)(void);
typedef MMRESULT(WINAPI* timeKillEvent_t)(UINT uTimerID);
typedef UINT(WINAPI* timeSetEvent_t)(UINT uDelay, UINT uResolution, LPTIMECALLBACK ptc, DWORD_PTR dwUser, UINT fuEvent);
typedef MMRESULT(WINAPI* waveInAddBuffer_t)(HWAVEIN hWaveIn, LPWAVEHDR pwh, UINT cbwh);
typedef MMRESULT(WINAPI* waveInClose_t)(HWAVEIN hWaveIn);
typedef MMRESULT(WINAPI* waveInGetDevCapsA_t)(UINT_PTR uDeviceID, LPWAVEINCAPSA pwic, UINT cbwic);
typedef MMRESULT(WINAPI* waveInGetDevCapsW_t)(UINT_PTR uDeviceID, LPWAVEINCAPSW pwic, UINT cbwic);
typedef MMRESULT(WINAPI* waveInGetErrorTextA_t)(MMRESULT mmrError, LPSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* waveInGetErrorTextW_t)(MMRESULT mmrError, LPWSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* waveInGetID_t)(HWAVEIN hWaveIn, LPUINT puDeviceID);
typedef UINT(WINAPI* waveInGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* waveInGetPosition_t)(HWAVEIN hWaveIn, LPMMTIME pmmt, UINT cbmmt);
typedef MMRESULT(WINAPI* waveInMessage_t)(HWAVEIN hWaveIn, UINT uMessage, DWORD_PTR dwParam1, DWORD_PTR dwParam2);
typedef MMRESULT(WINAPI* waveInOpen_t)(LPHWAVEIN phwi, UINT uDeviceID, LPCWAVEFORMATEX pwfx, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* waveInPrepareHeader_t)(HWAVEIN hwi, LPWAVEHDR pwh, UINT cbwh);
typedef MMRESULT(WINAPI* waveInReset_t)(HWAVEIN hwi);
typedef MMRESULT(WINAPI* waveInStart_t)(HWAVEIN hwi);
typedef MMRESULT(WINAPI* waveInStop_t)(HWAVEIN hwi);
typedef MMRESULT(WINAPI* waveInUnprepareHeader_t)(HWAVEIN hwi, LPWAVEHDR pwh, UINT cbwh);
typedef MMRESULT(WINAPI* waveOutBreakLoop_t)(HWAVEOUT hwo);
typedef MMRESULT(WINAPI* waveOutClose_t)(HWAVEOUT hwo);
typedef MMRESULT(WINAPI* waveOutGetDevCapsA_t)(UINT_PTR uDeviceID, LPWAVEOUTCAPSA pwoc, UINT cbwoc);
typedef MMRESULT(WINAPI* waveOutGetDevCapsW_t)(UINT_PTR uDeviceID, LPWAVEOUTCAPSW pwoc, UINT cbwoc);
typedef MMRESULT(WINAPI* waveOutGetErrorTextA_t)(MMRESULT mmrError, LPSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* waveOutGetErrorTextW_t)(MMRESULT mmrError, LPWSTR pszText, UINT cchText);
typedef MMRESULT(WINAPI* waveOutGetID_t)(HWAVEOUT hwo, LPUINT puDeviceID);
typedef UINT(WINAPI* waveOutGetNumDevs_t)(void);
typedef MMRESULT(WINAPI* waveOutGetPitch_t)(HWAVEOUT hwo, LPDWORD pdwPitch);
typedef MMRESULT(WINAPI* waveOutGetPlaybackRate_t)(HWAVEOUT hwo, LPDWORD pdwRate);
typedef MMRESULT(WINAPI* waveOutGetPosition_t)(HWAVEOUT hwo, LPMMTIME pmmt, UINT cbmmt);
typedef MMRESULT(WINAPI* waveOutGetVolume_t)(HWAVEOUT hwo, LPDWORD pdwVolume);
typedef MMRESULT(WINAPI* waveOutMessage_t)(HWAVEOUT hwo, UINT uMsg, DWORD_PTR dw1, DWORD_PTR dw2);
typedef MMRESULT(WINAPI* waveOutOpen_t)(LPHWAVEOUT phwo, UINT uDeviceID, LPCWAVEFORMATEX pwfx, DWORD_PTR dwCallback, DWORD_PTR dwInstance, DWORD fdwOpen);
typedef MMRESULT(WINAPI* waveOutPause_t)(HWAVEOUT hwo);
typedef MMRESULT(WINAPI* waveOutPrepareHeader_t)(HWAVEOUT hwo, LPWAVEHDR pwh, UINT cbwh);
typedef MMRESULT(WINAPI* waveOutReset_t)(HWAVEOUT hwo);
typedef MMRESULT(WINAPI* waveOutRestart_t)(HWAVEOUT hwo);
typedef MMRESULT(WINAPI* waveOutSetPitch_t)(HWAVEOUT hwo, DWORD dwPitch);
typedef MMRESULT(WINAPI* waveOutSetPlaybackRate_t)(HWAVEOUT hwo, DWORD dwRate);
typedef MMRESULT(WINAPI* waveOutSetVolume_t)(HWAVEOUT hwo, DWORD dwVolume);
typedef MMRESULT(WINAPI* waveOutUnprepareHeader_t)(HWAVEOUT hwo, LPWAVEHDR pwh, UINT cbwh);
typedef MMRESULT(WINAPI* waveOutWrite_t)(HWAVEOUT hwo, LPWAVEHDR pwh, UINT cbwh);
