# SPDX-License-Identifier: MIT
# Copyright © 2026 Paul Puhnaty

import sys
import hashlib
from collections import defaultdict
from pathlib import Path


def main():
    if len(sys.argv) != 2:
        print('Usage: stub_generator.py <api map>')
        sys.exit(1)

    config_file_path = Path(sys.argv[1])

    if not config_file_path.exists():
        print(f'stub_generator.py: File "{sys.argv[1]}" does not exist')
        sys.exit(1)

    hash_file_path = config_file_path.with_suffix('.hash')

    if current_hash := should_regenerate(config_file_path, hash_file_path):
        print('stub_generator.py: Regenerating stubs...')
        parsed = parse_api_map(config_file_path)
        store_hash(hash_file_path, current_hash)
        generate_stubs(parsed)
        print('stub_generator.py: Finished generating stubs')

    else:
        print('stub_generator.py: Stubs up to date')



def hash_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        while chunk := f.read(8192):
            h.update(chunk)
    return h.hexdigest()

def should_regenerate(config_path: Path, hash_path: Path) -> str:
    current_hash = hash_file(config_path)

    if not hash_path.exists():
        return current_hash

    with open(hash_path, 'r') as f:
        previous_hash = f.read().strip()

    if current_hash != previous_hash:
        return current_hash

    return ''

def store_hash(hash_path: Path, current_hash):
    with open(hash_path, 'w') as f:
        f.write(current_hash)


def clean_name(s):
    # Remove leading underscore
    if s.startswith('_'):
        s = s[1:]

    # Remove @ and everything after it
    s = s.split('@', 1)[0]

    return s


def assert_list_start(curr_library, in_list, buffer, filename, lineno):
    if not in_list:
        if (len(buffer) > 0) != (curr_library is not None):
            return
        else:
            assert_library_definition(curr_library, filename, lineno)
            print(f'{filename} ({lineno}): Unexpected list start; expected library name')
    else:
        print(f'{filename} ({lineno}): Unexpected nested list')

    sys.exit(1)

def assert_list_end(in_list, filename, lineno):
    if in_list:
        return
    else:
        print(f'{filename} ({lineno}): Unexpected end of list')

    sys.exit(1)

def assert_library_definition(curr_library, filename, lineno):
    if curr_library is None:
        return
    else:
        print(f'{filename} ({lineno}): Library name already specified; expected list start')

    sys.exit(1)

def parse_api_map(file: Path):
    api_map = defaultdict(list)
    curr_library = None
    in_list = False
    buffer = []

    with open(file, 'r') as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()

            if not line or line.startswith("#"):
                continue  # skip empty lines and comments

            for char in line:
                if char == '{':
                    assert_list_start(curr_library, in_list, buffer, file.name, lineno)
                    if len(buffer) > 0:
                        curr_library = ''.join(buffer)
                        buffer.clear()

                    in_list = True

                elif char == '}':
                    assert_list_end(in_list, file.name, lineno)
                    if len(buffer) > 0:
                        api_map[curr_library].append(''.join(buffer))
                        buffer.clear()

                    curr_library = None
                    in_list = False

                elif char.isalpha() or char.isdigit() or char == '_' or char == '@':
                    buffer.append(char)

                elif char == ' ' or char == '\t':
                    if len(buffer) > 0:
                        if in_list:
                            api_map[curr_library].append(''.join(buffer))
                            buffer.clear()

                        else:
                            assert_library_definition(curr_library, file.name, lineno)
                            curr_library = ''.join(buffer)
                            buffer.clear()

                else:
                    print(f'{file.name} ({lineno}): Unexpected symbol "{char}"')
                    sys.exit(1)

            if len(buffer) > 0:
                if in_list:
                    api_map[curr_library].append(''.join(buffer))
                    buffer.clear()

                else:
                    assert_library_definition(curr_library, file.name, lineno)
                    curr_library = ''.join(buffer)
                    buffer.clear()

    return dict(api_map)


def generate_stubs(api_map: dict):
    autogen_comment = '// Auto-generated by "stub_generator.py" - DO NOT EDIT\n'

    with open('ApiTables.inc', 'w') as f:
        f.write(autogen_comment)
        for key in api_map.keys():
            f.write(f'const char* {key}_apis[] = {{\n')
            
            for api in api_map[key]:
                f.write(f'    "{api}",\n')

            f.write(f'    nullptr\n}};\n')

    with open('HookLibraryCalls.inc', 'w') as f:
        f.write(autogen_comment)
        for key in api_map.keys():
            f.write(f'HookLibrary("{key}.dll", {key}_apis, wrapper);\n')

    with open(f'../ArmadaHooks/HookedApiDeclarations.inc', 'w') as f:
        f.write(autogen_comment)
        for key in api_map.keys():
            f.write(f'struct {key}_t {{\n')
            for api in api_map[key]:
                undecorated = clean_name(api)
                f.write(f'    decltype(&{undecorated}) {undecorated};\n')

            f.write(f'}} {key};\n')
            




if __name__ == '__main__':
    main()
